insert into AREA (AREA)
VALUES ('Matemática'), 
('Português'),
('Física'),
('Química'),
('História'),
('Geografia'),
('Inglês'),
('Espanhol'),
('Conhecimentos Gerais'),
('Biologia'),
('Filosofia'),
('Sociologia'),
('Cidadania'),
('Educação Física');

insert into ASSUNTO (ASSUNTO, ID_AREA)
values ('Trigonometria', 1),
    ('Geometria', 1),
    ('Função de 1º grau', 1),
    ('Função de 2º grau', 1),
    ('Polinômios', 1),
    ('Multiplicação', 1),
    ('Divisão', 1),
    ('Soma', 1),
    ('Subtração', 1),
    ('Juros Simples', 1),
    ('Juros Compostos', 1),
    ('Ortografia', 2),
    ('Uso de "m" ou "n"', 2),
    ('Uso de "ch" ou "x"', 2),
    ('Velocidade', 3),
    ('Força', 3),
    ('Óptica', 3),
    ('Tabela Periódica', 4),
    ('Elementos alcalinos', 4),
    ('Elementos de transição interna', 4),
    ('Elementos de transição externa', 4),
    ('História do Brasil', 5),
    ('Independência do Brasil', 5),
    ('Revolução Francesa', 5),
    ('Idade das Trevas', 5),
    ('Império Bizantino', 5),
    ('Divisão Geopolítica', 6),
    ('Divisão Geográfica', 6),
    ('Hidrografia do Brasil', 6),
    ('Geologia', 6),
    ('Verbo "to be"', 7),
    ('Infinitivo', 7),
    ('Pronomes de tratamento', 7),
    ('Pronomes pessoais', 7),
    ('Pronomes possessivos', 7),
    ('Pronomes pessoais', 8),
    ('Pronomes possessivos', 8),
    ('Pronomes de tratamento', 8),
    ('Política', 9),
    ('Mundo', 9),
    ('Seres vivos', 10),
    ('Célula', 10),
    ('Zoologia', 10),
    ('Botânica', 10),
    ('Platão', 11),
    ('Sócrates', 11),
    ('Descartes', 11),
    ('Karl Marx', 12),
    ('Engels', 12),
    ('Adam Smith', 12),
    ('Ética', 13),
    ('Moral', 13),
    ('Basquetebol', 14),
    ('Futebol', 14),
    ('Volêibol', 14),
    ('Handebol', 14);

insert into USUARIO (USUARIO, SENHA, NOME, CPF, EMAIL) 
values ('jairx', 'otaku', 'Jair Ferreira', '70020080021', 'jair_lindao@gmail.com'),
        ('vitim', 'pericles', 'Victor Pereira Albuquerque', '48624917651', 'vitimvitao@hotmail.com'),
        ('igueira', 'swift71', 'Igor dos Santos Vieira', '48621568463', 'igorte@gmail.com'),
        ('maximedium', 'maximezesse', 'Maximenio Soarea da Costa', '46846813146', 'maxemedia@hotmail.com'),
        ('davizeiro', 'direitatorta', 'Davi Santana Melino', '16546835646', 'daviguerreiro@gmail.com'),
        ('mlk31', 'afeeeee', 'Arthur Costa e Silva', '84867131646', 'espadaguerreira@hotmail.com'),
        ('daskebra', 'passaoucorre', 'Ferdinando Araquias Melanez', '64684133543', 'ferdinandzcantor@gmail.com'),
        ('swinguezeiro', 'swing69', 'Umberto Bessandre Linux', '54643164645', 'doisberto@gmail.com'),
        ('tomauma', 'gelada10de10', 'Linus Torvald Antenio', '64643115466', 'linuxzeiro@gmail.com'),
        ('sohvamo', 'jairjafui', 'Sulivan Alves Soares', '68443166878', 'melivan@hotmail.com');

insert into QUESTAO (PERGUNTA, RESPOSTA_CERTA, RESPOSTA2, RESPOSTA3, RESPOSTA4, RESPOSTA5, ID_USUARIO, ID_ASSUNTO)
values ('Quem descobriu o Brasil?', 'Cabral', 'Vasco da Gama', 'Bartolomeu', 'Anhanguera', 'Colombo', 7, 22),
        ('Como foi chamada a arte do período da Idade das Trevas?', 'Renascentista', 'Gótica', 'Cubista', 'Surrealista', 'Barroca', 5, 25), 
        ('Como se chama um triangulo com dois lados de tamanho igual?', 'Isosceles', 'Escaleno', 'Equilatero', 'Igualitário', 'Estatico', 5, 1), 
        ('Valor do seno de 45° é?', '1/sqrt(2)', '1/2', '30', '1', '1/sqrt(3)', 5, 1), 
        ('Em relação aos lados do triangulo, como calcular o valor de tangente?', 'cateto oposto/cateto adjacente', 'cateto oposto/hipotenusa', 'cateto adjacente/hipotenusa', 'cateto adjacente/cateto oposto', 'hipotenusa/cateto oposto', 5, 1), 
        ('Qual o valor do cosseno de 90°?', '0', '1', '90', '1/sqrt(2)', '1/sqrt(3)', 7, 1), 
        ('Qual o capital aplicado para render um montante de R$8000,00 reais depois de 12 meses de aplicação a uma taxa de 2% ao mês?', '6307,94', '7214,84', '6277,98', '7258,23', '6421,37', 7, 11), 
        ('Qual o juros compostos gerado por um investimento de R$3000,00 reais durante 3 meses a uma taxa de 2% ao mês?', '183,62', '254,27', '314,12', '157,29', '194,68', 8, 11);